server:
  port: 8081
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
spring:
  datasource:
    username: postgres
    password: 250407
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/finway_bot
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
debug: true
